// ==============================================================
// RTL generated by Scout HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.0
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _filter11x11_strm_ent_HH_
#define _filter11x11_strm_ent_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct filter11x11_strm_ent : public sc_module {
    // Port declarations 24
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<32> > width;
    sc_in< sc_lv<32> > height;
    sc_out< sc_lv<32> > width_out_din;
    sc_in< sc_logic > width_out_full_n;
    sc_out< sc_logic > width_out_write;
    sc_out< sc_lv<32> > width_out1_din;
    sc_in< sc_logic > width_out1_full_n;
    sc_out< sc_logic > width_out1_write;
    sc_out< sc_lv<32> > height_out_din;
    sc_in< sc_logic > height_out_full_n;
    sc_out< sc_logic > height_out_write;
    sc_out< sc_lv<32> > height_out2_din;
    sc_in< sc_logic > height_out2_full_n;
    sc_out< sc_logic > height_out2_write;


    // Module declarations
    filter11x11_strm_ent(sc_module_name name);
    SC_HAS_PROCESS(filter11x11_strm_ent);

    ~filter11x11_strm_ent();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > width_out_blk_n;
    sc_signal< sc_logic > width_out1_blk_n;
    sc_signal< sc_logic > height_out_blk_n;
    sc_signal< sc_logic > height_out2_blk_n;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_height_out2_blk_n();
    void thread_height_out2_din();
    void thread_height_out2_write();
    void thread_height_out_blk_n();
    void thread_height_out_din();
    void thread_height_out_write();
    void thread_internal_ap_ready();
    void thread_real_start();
    void thread_start_out();
    void thread_start_write();
    void thread_width_out1_blk_n();
    void thread_width_out1_din();
    void thread_width_out1_write();
    void thread_width_out_blk_n();
    void thread_width_out_din();
    void thread_width_out_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
