// ==============================================================
// RTL generated by Scout HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.0
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_VConvH_proc_HH_
#define _Loop_VConvH_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "filter11x11_strm_mux_104_32_1_1.h"
#include "filter11x11_strm_mul_32s_10ns_32_3_1.h"
#include "Loop_VConvH_proc_linebuf_0.h"
#include "Loop_VConvH_proc_filt11_coeff.h"

namespace ap_rtl {

struct Loop_VConvH_proc : public sc_module {
    // Port declarations 25
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > height_dout;
    sc_in< sc_logic > height_empty_n;
    sc_out< sc_logic > height_read;
    sc_in< sc_lv<32> > vconv_xlim_loc_dout;
    sc_in< sc_logic > vconv_xlim_loc_empty_n;
    sc_out< sc_logic > vconv_xlim_loc_read;
    sc_in< sc_lv<32> > hconv_V_dout;
    sc_in< sc_logic > hconv_V_empty_n;
    sc_out< sc_logic > hconv_V_read;
    sc_out< sc_lv<32> > vconv_V_din;
    sc_in< sc_logic > vconv_V_full_n;
    sc_out< sc_logic > vconv_V_write;
    sc_out< sc_lv<32> > height_out_din;
    sc_in< sc_logic > height_out_full_n;
    sc_out< sc_logic > height_out_write;
    sc_out< sc_lv<32> > vconv_xlim_loc_out_din;
    sc_in< sc_logic > vconv_xlim_loc_out_full_n;
    sc_out< sc_logic > vconv_xlim_loc_out_write;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    Loop_VConvH_proc(sc_module_name name);
    SC_HAS_PROCESS(Loop_VConvH_proc);

    ~Loop_VConvH_proc();

    sc_trace_file* mVcdFile;

    Loop_VConvH_proc_linebuf_0* linebuf_0_U;
    Loop_VConvH_proc_linebuf_0* linebuf_1_U;
    Loop_VConvH_proc_linebuf_0* linebuf_2_U;
    Loop_VConvH_proc_linebuf_0* linebuf_3_U;
    Loop_VConvH_proc_linebuf_0* linebuf_4_U;
    Loop_VConvH_proc_linebuf_0* linebuf_5_U;
    Loop_VConvH_proc_linebuf_0* linebuf_6_U;
    Loop_VConvH_proc_linebuf_0* linebuf_7_U;
    Loop_VConvH_proc_linebuf_0* linebuf_8_U;
    Loop_VConvH_proc_linebuf_0* linebuf_9_U;
    Loop_VConvH_proc_filt11_coeff* filt11_coeff_U;
    filter11x11_strm_mux_104_32_1_1<1,1,32,32,32,32,32,32,32,32,32,32,4,32>* filter11x11_strm_mux_104_32_1_1_U30;
    filter11x11_strm_mul_32s_10ns_32_3_1<1,3,32,10,32>* filter11x11_strm_mul_32s_10ns_32_3_1_U31;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > linebuf_0_ce0;
    sc_signal< sc_logic > linebuf_0_we0;
    sc_signal< sc_lv<32> > linebuf_0_q0;
    sc_signal< sc_logic > linebuf_1_ce0;
    sc_signal< sc_logic > linebuf_1_we0;
    sc_signal< sc_lv<32> > linebuf_1_q0;
    sc_signal< sc_logic > linebuf_2_ce0;
    sc_signal< sc_logic > linebuf_2_we0;
    sc_signal< sc_lv<32> > linebuf_2_q0;
    sc_signal< sc_logic > linebuf_3_ce0;
    sc_signal< sc_logic > linebuf_3_we0;
    sc_signal< sc_lv<32> > linebuf_3_q0;
    sc_signal< sc_logic > linebuf_4_ce0;
    sc_signal< sc_logic > linebuf_4_we0;
    sc_signal< sc_lv<32> > linebuf_4_q0;
    sc_signal< sc_logic > linebuf_5_ce0;
    sc_signal< sc_logic > linebuf_5_we0;
    sc_signal< sc_lv<32> > linebuf_5_q0;
    sc_signal< sc_logic > linebuf_6_ce0;
    sc_signal< sc_logic > linebuf_6_we0;
    sc_signal< sc_lv<32> > linebuf_6_q0;
    sc_signal< sc_logic > linebuf_7_ce0;
    sc_signal< sc_logic > linebuf_7_we0;
    sc_signal< sc_lv<32> > linebuf_7_q0;
    sc_signal< sc_logic > linebuf_8_ce0;
    sc_signal< sc_logic > linebuf_8_we0;
    sc_signal< sc_lv<32> > linebuf_8_q0;
    sc_signal< sc_logic > linebuf_9_ce0;
    sc_signal< sc_logic > linebuf_9_we0;
    sc_signal< sc_lv<32> > linebuf_9_q0;
    sc_signal< sc_lv<4> > filt11_coeff_address0;
    sc_signal< sc_logic > filt11_coeff_ce0;
    sc_signal< sc_lv<10> > filt11_coeff_q0;
    sc_signal< sc_logic > height_blk_n;
    sc_signal< sc_logic > vconv_xlim_loc_blk_n;
    sc_signal< sc_logic > hconv_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln186_fu_356_p2;
    sc_signal< sc_logic > vconv_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln191_fu_381_p2;
    sc_signal< sc_lv<1> > icmp_ln197_reg_464;
    sc_signal< sc_logic > height_out_blk_n;
    sc_signal< sc_logic > vconv_xlim_loc_out_blk_n;
    sc_signal< sc_lv<32> > height_read_reg_446;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > vconv_xlim_loc_read_reg_451;
    sc_signal< sc_lv<11> > col_fu_340_p2;
    sc_signal< sc_lv<11> > col_reg_459;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln197_fu_346_p2;
    sc_signal< sc_lv<1> > icmp_ln185_fu_335_p2;
    sc_signal< sc_lv<11> > row_fu_361_p2;
    sc_signal< sc_lv<11> > row_reg_471;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<32> > tmp_1_reg_476;
    sc_signal< sc_lv<11> > linebuf_0_addr_reg_481;
    sc_signal< sc_lv<11> > linebuf_1_addr_reg_486;
    sc_signal< sc_lv<11> > linebuf_2_addr_reg_491;
    sc_signal< sc_lv<11> > linebuf_3_addr_reg_496;
    sc_signal< sc_lv<11> > linebuf_4_addr_reg_501;
    sc_signal< sc_lv<11> > linebuf_5_addr_reg_506;
    sc_signal< sc_lv<11> > linebuf_6_addr_reg_511;
    sc_signal< sc_lv<11> > linebuf_7_addr_reg_516;
    sc_signal< sc_lv<11> > linebuf_8_addr_reg_521;
    sc_signal< sc_lv<11> > linebuf_9_addr_reg_526;
    sc_signal< sc_lv<4> > i_fu_387_p2;
    sc_signal< sc_lv<4> > i_reg_534;
    sc_signal< bool > ap_predicate_op73_write_state4;
    sc_signal< bool > ap_block_state4;
    sc_signal< sc_lv<32> > linebuf_0_load_reg_539;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > linebuf_1_load_reg_544;
    sc_signal< sc_lv<32> > linebuf_2_load_reg_549;
    sc_signal< sc_lv<32> > linebuf_3_load_reg_554;
    sc_signal< sc_lv<32> > linebuf_4_load_reg_559;
    sc_signal< sc_lv<32> > linebuf_5_load_reg_564;
    sc_signal< sc_lv<32> > linebuf_6_load_reg_569;
    sc_signal< sc_lv<32> > linebuf_7_load_reg_574;
    sc_signal< sc_lv<32> > linebuf_8_load_reg_579;
    sc_signal< sc_lv<32> > linebuf_9_load_reg_584;
    sc_signal< sc_lv<32> > vwin_val_fu_420_p3;
    sc_signal< sc_lv<32> > vwin_val_reg_594;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<10> > filt11_coeff_load_reg_609;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > grp_fu_430_p2;
    sc_signal< sc_lv<32> > mul_ln193_reg_619;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > out_val_fu_435_p2;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<11> > col1_0_i_i_i_reg_284;
    sc_signal< sc_lv<11> > row2_0_i_i_i_reg_295;
    sc_signal< sc_lv<32> > tmp_reg_306;
    sc_signal< sc_lv<4> > i5_0_i_i_i_reg_319;
    sc_signal< sc_lv<64> > zext_ln192_fu_367_p1;
    sc_signal< sc_lv<64> > zext_ln193_fu_393_p1;
    sc_signal< sc_lv<1> > icmp_ln194_fu_440_p2;
    sc_signal< sc_lv<32> > zext_ln185_fu_331_p1;
    sc_signal< sc_lv<32> > zext_ln186_fu_352_p1;
    sc_signal< sc_lv<1> > icmp_ln192_fu_398_p2;
    sc_signal< sc_lv<32> > tmp_4_fu_404_p12;
    sc_signal< sc_lv<10> > grp_fu_430_p1;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    sc_signal< sc_lv<32> > grp_fu_430_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_state9;
    static const sc_lv<10> ap_ST_fsm_state10;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<11> ap_const_lv11_9;
    static const sc_lv<4> ap_const_lv4_B;
    static const sc_lv<4> ap_const_lv4_A;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_block_state3();
    void thread_ap_block_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_predicate_op73_write_state4();
    void thread_ap_ready();
    void thread_col_fu_340_p2();
    void thread_filt11_coeff_address0();
    void thread_filt11_coeff_ce0();
    void thread_grp_fu_430_p1();
    void thread_grp_fu_430_p10();
    void thread_hconv_V_blk_n();
    void thread_hconv_V_read();
    void thread_height_blk_n();
    void thread_height_out_blk_n();
    void thread_height_out_din();
    void thread_height_out_write();
    void thread_height_read();
    void thread_i_fu_387_p2();
    void thread_icmp_ln185_fu_335_p2();
    void thread_icmp_ln186_fu_356_p2();
    void thread_icmp_ln191_fu_381_p2();
    void thread_icmp_ln192_fu_398_p2();
    void thread_icmp_ln194_fu_440_p2();
    void thread_icmp_ln197_fu_346_p2();
    void thread_linebuf_0_ce0();
    void thread_linebuf_0_we0();
    void thread_linebuf_1_ce0();
    void thread_linebuf_1_we0();
    void thread_linebuf_2_ce0();
    void thread_linebuf_2_we0();
    void thread_linebuf_3_ce0();
    void thread_linebuf_3_we0();
    void thread_linebuf_4_ce0();
    void thread_linebuf_4_we0();
    void thread_linebuf_5_ce0();
    void thread_linebuf_5_we0();
    void thread_linebuf_6_ce0();
    void thread_linebuf_6_we0();
    void thread_linebuf_7_ce0();
    void thread_linebuf_7_we0();
    void thread_linebuf_8_ce0();
    void thread_linebuf_8_we0();
    void thread_linebuf_9_ce0();
    void thread_linebuf_9_we0();
    void thread_out_val_fu_435_p2();
    void thread_row_fu_361_p2();
    void thread_vconv_V_blk_n();
    void thread_vconv_V_din();
    void thread_vconv_V_write();
    void thread_vconv_xlim_loc_blk_n();
    void thread_vconv_xlim_loc_out_blk_n();
    void thread_vconv_xlim_loc_out_din();
    void thread_vconv_xlim_loc_out_write();
    void thread_vconv_xlim_loc_read();
    void thread_vwin_val_fu_420_p3();
    void thread_zext_ln185_fu_331_p1();
    void thread_zext_ln186_fu_352_p1();
    void thread_zext_ln192_fu_367_p1();
    void thread_zext_ln193_fu_393_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
