// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.0
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_HConvH_proc8.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_HConvH_proc8::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_HConvH_proc8::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> Loop_HConvH_proc8::ap_ST_fsm_state1 = "1";
const sc_lv<6> Loop_HConvH_proc8::ap_ST_fsm_state2 = "10";
const sc_lv<6> Loop_HConvH_proc8::ap_ST_fsm_state3 = "100";
const sc_lv<6> Loop_HConvH_proc8::ap_ST_fsm_state4 = "1000";
const sc_lv<6> Loop_HConvH_proc8::ap_ST_fsm_pp0_stage0 = "10000";
const sc_lv<6> Loop_HConvH_proc8::ap_ST_fsm_state13 = "100000";
const bool Loop_HConvH_proc8::ap_const_boolean_1 = true;
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Loop_HConvH_proc8::ap_const_lv1_0 = "0";
const sc_lv<1> Loop_HConvH_proc8::ap_const_lv1_1 = "1";
const sc_lv<2> Loop_HConvH_proc8::ap_const_lv2_0 = "00";
const sc_lv<2> Loop_HConvH_proc8::ap_const_lv2_2 = "10";
const sc_lv<2> Loop_HConvH_proc8::ap_const_lv2_3 = "11";
const sc_lv<2> Loop_HConvH_proc8::ap_const_lv2_1 = "1";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_4 = "100";
const bool Loop_HConvH_proc8::ap_const_boolean_0 = false;
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_1 = "1";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_3 = "11";
const sc_lv<64> Loop_HConvH_proc8::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<11> Loop_HConvH_proc8::ap_const_lv11_0 = "00000000000";
const sc_lv<64> Loop_HConvH_proc8::ap_const_lv64_1 = "1";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_6F = "1101111";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_10A = "100001010";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_2D4 = "1011010100";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_335 = "1100110101";
const sc_lv<11> Loop_HConvH_proc8::ap_const_lv11_9 = "1001";
const sc_lv<11> Loop_HConvH_proc8::ap_const_lv11_1 = "1";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_1F2 = "111110010";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_5 = "101";
const sc_lv<32> Loop_HConvH_proc8::ap_const_lv32_2 = "10";

Loop_HConvH_proc8::Loop_HConvH_proc8(sc_module_name name) : sc_module(name), mVcdFile(0) {
    filter11x11_strm_mul_32ns_32ns_64_3_1_U12 = new filter11x11_strm_mul_32ns_32ns_64_3_1<1,3,32,32,64>("filter11x11_strm_mul_32ns_32ns_64_3_1_U12");
    filter11x11_strm_mul_32ns_32ns_64_3_1_U12->clk(ap_clk);
    filter11x11_strm_mul_32ns_32ns_64_3_1_U12->reset(ap_rst);
    filter11x11_strm_mul_32ns_32ns_64_3_1_U12->din0(grp_fu_165_p0);
    filter11x11_strm_mul_32ns_32ns_64_3_1_U12->din1(grp_fu_165_p1);
    filter11x11_strm_mul_32ns_32ns_64_3_1_U12->ce(ap_var_for_const0);
    filter11x11_strm_mul_32ns_32ns_64_3_1_U12->dout(grp_fu_165_p2);
    filter11x11_strm_mul_8ns_32s_32_3_1_U13 = new filter11x11_strm_mul_8ns_32s_32_3_1<1,3,8,32,32>("filter11x11_strm_mul_8ns_32s_32_3_1_U13");
    filter11x11_strm_mul_8ns_32s_32_3_1_U13->clk(ap_clk);
    filter11x11_strm_mul_8ns_32s_32_3_1_U13->reset(ap_rst);
    filter11x11_strm_mul_8ns_32s_32_3_1_U13->din0(grp_fu_277_p0);
    filter11x11_strm_mul_8ns_32s_32_3_1_U13->din1(hwin_1_fu_76);
    filter11x11_strm_mul_8ns_32s_32_3_1_U13->ce(grp_fu_277_ce);
    filter11x11_strm_mul_8ns_32s_32_3_1_U13->dout(grp_fu_277_p2);
    filter11x11_strm_mul_10ns_32s_32_3_1_U14 = new filter11x11_strm_mul_10ns_32s_32_3_1<1,3,10,32,32>("filter11x11_strm_mul_10ns_32s_32_3_1_U14");
    filter11x11_strm_mul_10ns_32s_32_3_1_U14->clk(ap_clk);
    filter11x11_strm_mul_10ns_32s_32_3_1_U14->reset(ap_rst);
    filter11x11_strm_mul_10ns_32s_32_3_1_U14->din0(grp_fu_283_p0);
    filter11x11_strm_mul_10ns_32s_32_3_1_U14->din1(hwin_2_fu_80);
    filter11x11_strm_mul_10ns_32s_32_3_1_U14->ce(grp_fu_283_ce);
    filter11x11_strm_mul_10ns_32s_32_3_1_U14->dout(grp_fu_283_p2);
    filter11x11_strm_mul_11ns_32s_32_3_1_U15 = new filter11x11_strm_mul_11ns_32s_32_3_1<1,3,11,32,32>("filter11x11_strm_mul_11ns_32s_32_3_1_U15");
    filter11x11_strm_mul_11ns_32s_32_3_1_U15->clk(ap_clk);
    filter11x11_strm_mul_11ns_32s_32_3_1_U15->reset(ap_rst);
    filter11x11_strm_mul_11ns_32s_32_3_1_U15->din0(grp_fu_289_p0);
    filter11x11_strm_mul_11ns_32s_32_3_1_U15->din1(hwin_4_fu_88);
    filter11x11_strm_mul_11ns_32s_32_3_1_U15->ce(grp_fu_289_ce);
    filter11x11_strm_mul_11ns_32s_32_3_1_U15->dout(grp_fu_289_p2);
    filter11x11_strm_mul_11ns_32s_32_3_1_U16 = new filter11x11_strm_mul_11ns_32s_32_3_1<1,3,11,32,32>("filter11x11_strm_mul_11ns_32s_32_3_1_U16");
    filter11x11_strm_mul_11ns_32s_32_3_1_U16->clk(ap_clk);
    filter11x11_strm_mul_11ns_32s_32_3_1_U16->reset(ap_rst);
    filter11x11_strm_mul_11ns_32s_32_3_1_U16->din0(grp_fu_295_p0);
    filter11x11_strm_mul_11ns_32s_32_3_1_U16->din1(hwin_5_fu_92);
    filter11x11_strm_mul_11ns_32s_32_3_1_U16->ce(grp_fu_295_ce);
    filter11x11_strm_mul_11ns_32s_32_3_1_U16->dout(grp_fu_295_p2);
    filter11x11_strm_mul_10ns_32s_32_3_1_U17 = new filter11x11_strm_mul_10ns_32s_32_3_1<1,3,10,32,32>("filter11x11_strm_mul_10ns_32s_32_3_1_U17");
    filter11x11_strm_mul_10ns_32s_32_3_1_U17->clk(ap_clk);
    filter11x11_strm_mul_10ns_32s_32_3_1_U17->reset(ap_rst);
    filter11x11_strm_mul_10ns_32s_32_3_1_U17->din0(grp_fu_301_p0);
    filter11x11_strm_mul_10ns_32s_32_3_1_U17->din1(hwin_8_fu_104);
    filter11x11_strm_mul_10ns_32s_32_3_1_U17->ce(grp_fu_301_ce);
    filter11x11_strm_mul_10ns_32s_32_3_1_U17->dout(grp_fu_301_p2);
    filter11x11_strm_mul_8ns_32s_32_3_1_U18 = new filter11x11_strm_mul_8ns_32s_32_3_1<1,3,8,32,32>("filter11x11_strm_mul_8ns_32s_32_3_1_U18");
    filter11x11_strm_mul_8ns_32s_32_3_1_U18->clk(ap_clk);
    filter11x11_strm_mul_8ns_32s_32_3_1_U18->reset(ap_rst);
    filter11x11_strm_mul_8ns_32s_32_3_1_U18->din0(grp_fu_307_p0);
    filter11x11_strm_mul_8ns_32s_32_3_1_U18->din1(hwin_9_fu_108);
    filter11x11_strm_mul_8ns_32s_32_3_1_U18->ce(grp_fu_307_ce);
    filter11x11_strm_mul_8ns_32s_32_3_1_U18->dout(grp_fu_307_p2);
    filter11x11_strm_mul_11ns_32s_32_3_1_U19 = new filter11x11_strm_mul_11ns_32s_32_3_1<1,3,11,32,32>("filter11x11_strm_mul_11ns_32s_32_3_1_U19");
    filter11x11_strm_mul_11ns_32s_32_3_1_U19->clk(ap_clk);
    filter11x11_strm_mul_11ns_32s_32_3_1_U19->reset(ap_rst);
    filter11x11_strm_mul_11ns_32s_32_3_1_U19->din0(grp_fu_330_p0);
    filter11x11_strm_mul_11ns_32s_32_3_1_U19->din1(hwin_6_load_reg_540);
    filter11x11_strm_mul_11ns_32s_32_3_1_U19->ce(grp_fu_330_ce);
    filter11x11_strm_mul_11ns_32s_32_3_1_U19->dout(grp_fu_330_p2);
    filter11x11_strm_mul_10ns_32s_32_3_1_U20 = new filter11x11_strm_mul_10ns_32s_32_3_1<1,3,10,32,32>("filter11x11_strm_mul_10ns_32s_32_3_1_U20");
    filter11x11_strm_mul_10ns_32s_32_3_1_U20->clk(ap_clk);
    filter11x11_strm_mul_10ns_32s_32_3_1_U20->reset(ap_rst);
    filter11x11_strm_mul_10ns_32s_32_3_1_U20->din0(grp_fu_335_p0);
    filter11x11_strm_mul_10ns_32s_32_3_1_U20->din1(hwin_7_load_reg_545);
    filter11x11_strm_mul_10ns_32s_32_3_1_U20->ce(grp_fu_335_ce);
    filter11x11_strm_mul_10ns_32s_32_3_1_U20->dout(grp_fu_335_p2);
    filter11x11_strm_mul_10ns_32s_32_3_1_U21 = new filter11x11_strm_mul_10ns_32s_32_3_1<1,3,10,32,32>("filter11x11_strm_mul_10ns_32s_32_3_1_U21");
    filter11x11_strm_mul_10ns_32s_32_3_1_U21->clk(ap_clk);
    filter11x11_strm_mul_10ns_32s_32_3_1_U21->reset(ap_rst);
    filter11x11_strm_mul_10ns_32s_32_3_1_U21->din0(grp_fu_340_p0);
    filter11x11_strm_mul_10ns_32s_32_3_1_U21->din1(hwin_3_load_reg_525_pp0_iter1_reg);
    filter11x11_strm_mul_10ns_32s_32_3_1_U21->ce(grp_fu_340_ce);
    filter11x11_strm_mul_10ns_32s_32_3_1_U21->dout(grp_fu_340_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln168_fu_215_p2);
    sensitive << ( indvar_flatten_reg_137 );

    SC_METHOD(thread_add_ln176_10_fu_408_p2);
    sensitive << ( add_ln176_9_reg_649 );
    sensitive << ( add_ln176_6_fu_404_p2 );

    SC_METHOD(thread_add_ln176_1_fu_371_p2);
    sensitive << ( add_ln176_fu_365_p2 );
    sensitive << ( shl_ln176_3_fu_360_p2 );

    SC_METHOD(thread_add_ln176_2_fu_377_p2);
    sensitive << ( mul_ln176_reg_584 );
    sensitive << ( mul_ln176_1_reg_589 );

    SC_METHOD(thread_add_ln176_3_fu_381_p2);
    sensitive << ( add_ln176_2_fu_377_p2 );
    sensitive << ( shl_ln176_1_fu_350_p2 );

    SC_METHOD(thread_add_ln176_4_fu_413_p2);
    sensitive << ( add_ln176_1_reg_624_pp0_iter5_reg );
    sensitive << ( add_ln176_3_reg_629_pp0_iter5_reg );

    SC_METHOD(thread_add_ln176_5_fu_387_p2);
    sensitive << ( mul_ln176_3_reg_594 );
    sensitive << ( mul_ln176_4_reg_599 );

    SC_METHOD(thread_add_ln176_6_fu_404_p2);
    sensitive << ( add_ln176_5_reg_634_pp0_iter4_reg );
    sensitive << ( mul_ln176_2_reg_644 );

    SC_METHOD(thread_add_ln176_7_fu_395_p2);
    sensitive << ( mul_ln176_5_reg_614 );
    sensitive << ( mul_ln176_6_reg_619 );

    SC_METHOD(thread_add_ln176_8_fu_391_p2);
    sensitive << ( mul_ln176_7_reg_604 );
    sensitive << ( mul_ln176_8_reg_609 );

    SC_METHOD(thread_add_ln176_9_fu_399_p2);
    sensitive << ( add_ln176_8_reg_639 );
    sensitive << ( add_ln176_7_fu_395_p2 );

    SC_METHOD(thread_add_ln176_fu_365_p2);
    sensitive << ( shl_ln176_2_fu_355_p2 );
    sensitive << ( shl_ln176_fu_345_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( src_V_0_vld_out );
    sensitive << ( hconv_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln168_fu_210_p2 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln178_reg_575_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( src_V_0_vld_out );
    sensitive << ( hconv_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln168_fu_210_p2 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln178_reg_575_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( src_V_0_vld_out );
    sensitive << ( hconv_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln168_fu_210_p2 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln178_reg_575_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( height_empty_n );
    sensitive << ( width_empty_n );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter7);
    sensitive << ( hconv_V_full_n );
    sensitive << ( icmp_ln178_reg_575_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter0);
    sensitive << ( src_V_0_vld_out );
    sensitive << ( icmp_ln168_fu_210_p2 );

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter4);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state5);
    sensitive << ( icmp_ln168_fu_210_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_grp_fu_165_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fu_165_p00 );

    SC_METHOD(thread_grp_fu_165_p00);
    sensitive << ( width_read_reg_488 );

    SC_METHOD(thread_grp_fu_165_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fu_165_p10 );

    SC_METHOD(thread_grp_fu_165_p10);
    sensitive << ( height_read_reg_483 );

    SC_METHOD(thread_grp_fu_277_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_277_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_283_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_283_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_289_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_289_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_295_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_295_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_301_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_301_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_307_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_307_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_330_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_330_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_grp_fu_335_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_335_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_grp_fu_340_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_340_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_hconv_V_blk_n);
    sensitive << ( hconv_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln178_reg_575_pp0_iter6_reg );

    SC_METHOD(thread_hconv_V_din);
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln178_reg_575_pp0_iter6_reg );
    sensitive << ( tmp_reg_659 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_hconv_V_write);
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln178_reg_575_pp0_iter6_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_height_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( height_empty_n );

    SC_METHOD(thread_height_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( height_empty_n );
    sensitive << ( width_empty_n );

    SC_METHOD(thread_icmp_ln168_fu_210_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( indvar_flatten_reg_137 );
    sensitive << ( bound_reg_504 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln169_fu_205_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( width_read_reg_488 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( zext_ln169_fu_201_p1 );

    SC_METHOD(thread_icmp_ln178_fu_313_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln168_fu_210_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( select_ln169_fu_269_p3 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_row_fu_324_p2);
    sensitive << ( select_ln169_fu_269_p3 );

    SC_METHOD(thread_select_ln169_fu_269_p3);
    sensitive << ( row_0_i_i_reg_148 );
    sensitive << ( icmp_ln169_fu_205_p2 );

    SC_METHOD(thread_shl_ln176_1_fu_350_p2);
    sensitive << ( hwin_1_1_i_load_reg_509_pp0_iter2_reg );

    SC_METHOD(thread_shl_ln176_2_fu_355_p2);
    sensitive << ( tmp_2_reg_569_pp0_iter2_reg );

    SC_METHOD(thread_shl_ln176_3_fu_360_p2);
    sensitive << ( tmp_2_reg_569_pp0_iter2_reg );

    SC_METHOD(thread_shl_ln176_fu_345_p2);
    sensitive << ( hwin_1_1_i_load_reg_509_pp0_iter2_reg );

    SC_METHOD(thread_src_V_0_ack_in);
    sensitive << ( src_V_0_state );

    SC_METHOD(thread_src_V_0_ack_out);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln168_fu_210_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_src_V_0_data_out);
    sensitive << ( src_V_0_payload_A );
    sensitive << ( src_V_0_payload_B );
    sensitive << ( src_V_0_sel );

    SC_METHOD(thread_src_V_0_load_A);
    sensitive << ( src_V_0_sel_wr );
    sensitive << ( src_V_0_state_cmp_full );

    SC_METHOD(thread_src_V_0_load_B);
    sensitive << ( src_V_0_sel_wr );
    sensitive << ( src_V_0_state_cmp_full );

    SC_METHOD(thread_src_V_0_sel);
    sensitive << ( src_V_0_sel_rd );

    SC_METHOD(thread_src_V_0_state_cmp_full);
    sensitive << ( src_V_0_state );

    SC_METHOD(thread_src_V_0_vld_in);
    sensitive << ( src_V_TVALID );

    SC_METHOD(thread_src_V_0_vld_out);
    sensitive << ( src_V_0_state );

    SC_METHOD(thread_src_V_TDATA_blk_n);
    sensitive << ( src_V_0_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln168_fu_210_p2 );

    SC_METHOD(thread_src_V_TREADY);
    sensitive << ( src_V_0_state );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_fu_417_p2);
    sensitive << ( add_ln176_10_reg_654 );
    sensitive << ( add_ln176_4_fu_413_p2 );

    SC_METHOD(thread_width_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( width_empty_n );

    SC_METHOD(thread_width_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( height_empty_n );
    sensitive << ( width_empty_n );

    SC_METHOD(thread_zext_ln169_fu_201_p1);
    sensitive << ( row_0_i_i_reg_148 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( height_empty_n );
    sensitive << ( width_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln168_fu_210_p2 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter6 );

    SC_THREAD(thread_ap_var_for_const0);

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000001";
    src_V_0_sel_rd = SC_LOGIC_0;
    src_V_0_sel_wr = SC_LOGIC_0;
    src_V_0_state = "00";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_HConvH_proc8_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, height_dout, "(port)height_dout");
    sc_trace(mVcdFile, height_empty_n, "(port)height_empty_n");
    sc_trace(mVcdFile, height_read, "(port)height_read");
    sc_trace(mVcdFile, width_dout, "(port)width_dout");
    sc_trace(mVcdFile, width_empty_n, "(port)width_empty_n");
    sc_trace(mVcdFile, width_read, "(port)width_read");
    sc_trace(mVcdFile, src_V_TDATA, "(port)src_V_TDATA");
    sc_trace(mVcdFile, src_V_TVALID, "(port)src_V_TVALID");
    sc_trace(mVcdFile, src_V_TREADY, "(port)src_V_TREADY");
    sc_trace(mVcdFile, hconv_V_din, "(port)hconv_V_din");
    sc_trace(mVcdFile, hconv_V_full_n, "(port)hconv_V_full_n");
    sc_trace(mVcdFile, hconv_V_write, "(port)hconv_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, src_V_0_data_out, "src_V_0_data_out");
    sc_trace(mVcdFile, src_V_0_vld_in, "src_V_0_vld_in");
    sc_trace(mVcdFile, src_V_0_vld_out, "src_V_0_vld_out");
    sc_trace(mVcdFile, src_V_0_ack_in, "src_V_0_ack_in");
    sc_trace(mVcdFile, src_V_0_ack_out, "src_V_0_ack_out");
    sc_trace(mVcdFile, src_V_0_payload_A, "src_V_0_payload_A");
    sc_trace(mVcdFile, src_V_0_payload_B, "src_V_0_payload_B");
    sc_trace(mVcdFile, src_V_0_sel_rd, "src_V_0_sel_rd");
    sc_trace(mVcdFile, src_V_0_sel_wr, "src_V_0_sel_wr");
    sc_trace(mVcdFile, src_V_0_sel, "src_V_0_sel");
    sc_trace(mVcdFile, src_V_0_load_A, "src_V_0_load_A");
    sc_trace(mVcdFile, src_V_0_load_B, "src_V_0_load_B");
    sc_trace(mVcdFile, src_V_0_state, "src_V_0_state");
    sc_trace(mVcdFile, src_V_0_state_cmp_full, "src_V_0_state_cmp_full");
    sc_trace(mVcdFile, height_blk_n, "height_blk_n");
    sc_trace(mVcdFile, width_blk_n, "width_blk_n");
    sc_trace(mVcdFile, src_V_TDATA_blk_n, "src_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln168_fu_210_p2, "icmp_ln168_fu_210_p2");
    sc_trace(mVcdFile, hconv_V_blk_n, "hconv_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, icmp_ln178_reg_575, "icmp_ln178_reg_575");
    sc_trace(mVcdFile, icmp_ln178_reg_575_pp0_iter6_reg, "icmp_ln178_reg_575_pp0_iter6_reg");
    sc_trace(mVcdFile, indvar_flatten_reg_137, "indvar_flatten_reg_137");
    sc_trace(mVcdFile, row_0_i_i_reg_148, "row_0_i_i_reg_148");
    sc_trace(mVcdFile, height_read_reg_483, "height_read_reg_483");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, width_read_reg_488, "width_read_reg_488");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_fu_165_p2, "grp_fu_165_p2");
    sc_trace(mVcdFile, bound_reg_504, "bound_reg_504");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, hwin_1_1_i_load_reg_509, "hwin_1_1_i_load_reg_509");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter0, "ap_block_state5_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter2, "ap_block_state7_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter3, "ap_block_state8_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter4, "ap_block_state9_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter5, "ap_block_state10_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter6, "ap_block_state11_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter7, "ap_block_state12_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, hwin_1_1_i_load_reg_509_pp0_iter1_reg, "hwin_1_1_i_load_reg_509_pp0_iter1_reg");
    sc_trace(mVcdFile, hwin_1_1_i_load_reg_509_pp0_iter2_reg, "hwin_1_1_i_load_reg_509_pp0_iter2_reg");
    sc_trace(mVcdFile, hwin_3_load_reg_525, "hwin_3_load_reg_525");
    sc_trace(mVcdFile, hwin_3_load_reg_525_pp0_iter1_reg, "hwin_3_load_reg_525_pp0_iter1_reg");
    sc_trace(mVcdFile, hwin_6_load_reg_540, "hwin_6_load_reg_540");
    sc_trace(mVcdFile, hwin_7_load_reg_545, "hwin_7_load_reg_545");
    sc_trace(mVcdFile, icmp_ln168_reg_555, "icmp_ln168_reg_555");
    sc_trace(mVcdFile, icmp_ln168_reg_555_pp0_iter1_reg, "icmp_ln168_reg_555_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln168_reg_555_pp0_iter2_reg, "icmp_ln168_reg_555_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln168_reg_555_pp0_iter3_reg, "icmp_ln168_reg_555_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln168_reg_555_pp0_iter4_reg, "icmp_ln168_reg_555_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln168_reg_555_pp0_iter5_reg, "icmp_ln168_reg_555_pp0_iter5_reg");
    sc_trace(mVcdFile, add_ln168_fu_215_p2, "add_ln168_fu_215_p2");
    sc_trace(mVcdFile, tmp_2_reg_569, "tmp_2_reg_569");
    sc_trace(mVcdFile, tmp_2_reg_569_pp0_iter1_reg, "tmp_2_reg_569_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_2_reg_569_pp0_iter2_reg, "tmp_2_reg_569_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln178_fu_313_p2, "icmp_ln178_fu_313_p2");
    sc_trace(mVcdFile, icmp_ln178_reg_575_pp0_iter1_reg, "icmp_ln178_reg_575_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln178_reg_575_pp0_iter2_reg, "icmp_ln178_reg_575_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln178_reg_575_pp0_iter3_reg, "icmp_ln178_reg_575_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln178_reg_575_pp0_iter4_reg, "icmp_ln178_reg_575_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln178_reg_575_pp0_iter5_reg, "icmp_ln178_reg_575_pp0_iter5_reg");
    sc_trace(mVcdFile, row_fu_324_p2, "row_fu_324_p2");
    sc_trace(mVcdFile, grp_fu_277_p2, "grp_fu_277_p2");
    sc_trace(mVcdFile, mul_ln176_reg_584, "mul_ln176_reg_584");
    sc_trace(mVcdFile, grp_fu_283_p2, "grp_fu_283_p2");
    sc_trace(mVcdFile, mul_ln176_1_reg_589, "mul_ln176_1_reg_589");
    sc_trace(mVcdFile, grp_fu_289_p2, "grp_fu_289_p2");
    sc_trace(mVcdFile, mul_ln176_3_reg_594, "mul_ln176_3_reg_594");
    sc_trace(mVcdFile, grp_fu_295_p2, "grp_fu_295_p2");
    sc_trace(mVcdFile, mul_ln176_4_reg_599, "mul_ln176_4_reg_599");
    sc_trace(mVcdFile, grp_fu_301_p2, "grp_fu_301_p2");
    sc_trace(mVcdFile, mul_ln176_7_reg_604, "mul_ln176_7_reg_604");
    sc_trace(mVcdFile, grp_fu_307_p2, "grp_fu_307_p2");
    sc_trace(mVcdFile, mul_ln176_8_reg_609, "mul_ln176_8_reg_609");
    sc_trace(mVcdFile, grp_fu_330_p2, "grp_fu_330_p2");
    sc_trace(mVcdFile, mul_ln176_5_reg_614, "mul_ln176_5_reg_614");
    sc_trace(mVcdFile, grp_fu_335_p2, "grp_fu_335_p2");
    sc_trace(mVcdFile, mul_ln176_6_reg_619, "mul_ln176_6_reg_619");
    sc_trace(mVcdFile, add_ln176_1_fu_371_p2, "add_ln176_1_fu_371_p2");
    sc_trace(mVcdFile, add_ln176_1_reg_624, "add_ln176_1_reg_624");
    sc_trace(mVcdFile, add_ln176_1_reg_624_pp0_iter4_reg, "add_ln176_1_reg_624_pp0_iter4_reg");
    sc_trace(mVcdFile, add_ln176_1_reg_624_pp0_iter5_reg, "add_ln176_1_reg_624_pp0_iter5_reg");
    sc_trace(mVcdFile, add_ln176_3_fu_381_p2, "add_ln176_3_fu_381_p2");
    sc_trace(mVcdFile, add_ln176_3_reg_629, "add_ln176_3_reg_629");
    sc_trace(mVcdFile, add_ln176_3_reg_629_pp0_iter4_reg, "add_ln176_3_reg_629_pp0_iter4_reg");
    sc_trace(mVcdFile, add_ln176_3_reg_629_pp0_iter5_reg, "add_ln176_3_reg_629_pp0_iter5_reg");
    sc_trace(mVcdFile, add_ln176_5_fu_387_p2, "add_ln176_5_fu_387_p2");
    sc_trace(mVcdFile, add_ln176_5_reg_634, "add_ln176_5_reg_634");
    sc_trace(mVcdFile, add_ln176_5_reg_634_pp0_iter4_reg, "add_ln176_5_reg_634_pp0_iter4_reg");
    sc_trace(mVcdFile, add_ln176_8_fu_391_p2, "add_ln176_8_fu_391_p2");
    sc_trace(mVcdFile, add_ln176_8_reg_639, "add_ln176_8_reg_639");
    sc_trace(mVcdFile, grp_fu_340_p2, "grp_fu_340_p2");
    sc_trace(mVcdFile, mul_ln176_2_reg_644, "mul_ln176_2_reg_644");
    sc_trace(mVcdFile, add_ln176_9_fu_399_p2, "add_ln176_9_fu_399_p2");
    sc_trace(mVcdFile, add_ln176_9_reg_649, "add_ln176_9_reg_649");
    sc_trace(mVcdFile, add_ln176_10_fu_408_p2, "add_ln176_10_fu_408_p2");
    sc_trace(mVcdFile, add_ln176_10_reg_654, "add_ln176_10_reg_654");
    sc_trace(mVcdFile, tmp_fu_417_p2, "tmp_fu_417_p2");
    sc_trace(mVcdFile, tmp_reg_659, "tmp_reg_659");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state5, "ap_condition_pp0_exit_iter0_state5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, hwin_1_1_i_fu_72, "hwin_1_1_i_fu_72");
    sc_trace(mVcdFile, hwin_1_fu_76, "hwin_1_fu_76");
    sc_trace(mVcdFile, hwin_2_fu_80, "hwin_2_fu_80");
    sc_trace(mVcdFile, hwin_3_fu_84, "hwin_3_fu_84");
    sc_trace(mVcdFile, hwin_4_fu_88, "hwin_4_fu_88");
    sc_trace(mVcdFile, hwin_5_fu_92, "hwin_5_fu_92");
    sc_trace(mVcdFile, hwin_6_fu_96, "hwin_6_fu_96");
    sc_trace(mVcdFile, hwin_7_fu_100, "hwin_7_fu_100");
    sc_trace(mVcdFile, hwin_8_fu_104, "hwin_8_fu_104");
    sc_trace(mVcdFile, hwin_9_fu_108, "hwin_9_fu_108");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_165_p0, "grp_fu_165_p0");
    sc_trace(mVcdFile, grp_fu_165_p1, "grp_fu_165_p1");
    sc_trace(mVcdFile, zext_ln169_fu_201_p1, "zext_ln169_fu_201_p1");
    sc_trace(mVcdFile, icmp_ln169_fu_205_p2, "icmp_ln169_fu_205_p2");
    sc_trace(mVcdFile, grp_fu_277_p0, "grp_fu_277_p0");
    sc_trace(mVcdFile, grp_fu_283_p0, "grp_fu_283_p0");
    sc_trace(mVcdFile, grp_fu_289_p0, "grp_fu_289_p0");
    sc_trace(mVcdFile, grp_fu_295_p0, "grp_fu_295_p0");
    sc_trace(mVcdFile, grp_fu_301_p0, "grp_fu_301_p0");
    sc_trace(mVcdFile, grp_fu_307_p0, "grp_fu_307_p0");
    sc_trace(mVcdFile, select_ln169_fu_269_p3, "select_ln169_fu_269_p3");
    sc_trace(mVcdFile, grp_fu_330_p0, "grp_fu_330_p0");
    sc_trace(mVcdFile, grp_fu_335_p0, "grp_fu_335_p0");
    sc_trace(mVcdFile, grp_fu_340_p0, "grp_fu_340_p0");
    sc_trace(mVcdFile, shl_ln176_2_fu_355_p2, "shl_ln176_2_fu_355_p2");
    sc_trace(mVcdFile, shl_ln176_fu_345_p2, "shl_ln176_fu_345_p2");
    sc_trace(mVcdFile, add_ln176_fu_365_p2, "add_ln176_fu_365_p2");
    sc_trace(mVcdFile, shl_ln176_3_fu_360_p2, "shl_ln176_3_fu_360_p2");
    sc_trace(mVcdFile, add_ln176_2_fu_377_p2, "add_ln176_2_fu_377_p2");
    sc_trace(mVcdFile, shl_ln176_1_fu_350_p2, "shl_ln176_1_fu_350_p2");
    sc_trace(mVcdFile, add_ln176_7_fu_395_p2, "add_ln176_7_fu_395_p2");
    sc_trace(mVcdFile, add_ln176_6_fu_404_p2, "add_ln176_6_fu_404_p2");
    sc_trace(mVcdFile, add_ln176_4_fu_413_p2, "add_ln176_4_fu_413_p2");
    sc_trace(mVcdFile, grp_fu_277_ce, "grp_fu_277_ce");
    sc_trace(mVcdFile, grp_fu_283_ce, "grp_fu_283_ce");
    sc_trace(mVcdFile, grp_fu_289_ce, "grp_fu_289_ce");
    sc_trace(mVcdFile, grp_fu_295_ce, "grp_fu_295_ce");
    sc_trace(mVcdFile, grp_fu_301_ce, "grp_fu_301_ce");
    sc_trace(mVcdFile, grp_fu_307_ce, "grp_fu_307_ce");
    sc_trace(mVcdFile, grp_fu_330_ce, "grp_fu_330_ce");
    sc_trace(mVcdFile, grp_fu_335_ce, "grp_fu_335_ce");
    sc_trace(mVcdFile, grp_fu_340_ce, "grp_fu_340_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_165_p00, "grp_fu_165_p00");
    sc_trace(mVcdFile, grp_fu_165_p10, "grp_fu_165_p10");
#endif

    }
}

Loop_HConvH_proc8::~Loop_HConvH_proc8() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete filter11x11_strm_mul_32ns_32ns_64_3_1_U12;
    delete filter11x11_strm_mul_8ns_32s_32_3_1_U13;
    delete filter11x11_strm_mul_10ns_32s_32_3_1_U14;
    delete filter11x11_strm_mul_11ns_32s_32_3_1_U15;
    delete filter11x11_strm_mul_11ns_32s_32_3_1_U16;
    delete filter11x11_strm_mul_10ns_32s_32_3_1_U17;
    delete filter11x11_strm_mul_8ns_32s_32_3_1_U18;
    delete filter11x11_strm_mul_11ns_32s_32_3_1_U19;
    delete filter11x11_strm_mul_10ns_32s_32_3_1_U20;
    delete filter11x11_strm_mul_10ns_32s_32_3_1_U21;
}

void Loop_HConvH_proc8::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Loop_HConvH_proc8::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state5.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp0_iter7 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        indvar_flatten_reg_137 = add_ln168_fu_215_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        indvar_flatten_reg_137 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        row_0_i_i_reg_148 = row_fu_324_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        row_0_i_i_reg_148 = ap_const_lv11_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        src_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_vld_out.read()))) {
            src_V_0_sel_rd =  (sc_logic) (~src_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        src_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_ack_in.read()))) {
            src_V_0_sel_wr =  (sc_logic) (~src_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        src_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(src_V_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(src_V_0_state.read(), ap_const_lv2_2)))) {
            src_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(src_V_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(src_V_0_state.read(), ap_const_lv2_1)))) {
            src_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(src_V_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(src_V_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(src_V_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_ack_out.read()))))) {
            src_V_0_state = ap_const_lv2_3;
        } else {
            src_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_reg_555_pp0_iter4_reg.read()))) {
        add_ln176_10_reg_654 = add_ln176_10_fu_408_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_reg_555_pp0_iter2_reg.read()))) {
        add_ln176_1_reg_624 = add_ln176_1_fu_371_p2.read();
        add_ln176_3_reg_629 = add_ln176_3_fu_381_p2.read();
        add_ln176_5_reg_634 = add_ln176_5_fu_387_p2.read();
        add_ln176_8_reg_639 = add_ln176_8_fu_391_p2.read();
        mul_ln176_5_reg_614 = grp_fu_330_p2.read();
        mul_ln176_6_reg_619 = grp_fu_335_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        add_ln176_1_reg_624_pp0_iter4_reg = add_ln176_1_reg_624.read();
        add_ln176_1_reg_624_pp0_iter5_reg = add_ln176_1_reg_624_pp0_iter4_reg.read();
        add_ln176_3_reg_629_pp0_iter4_reg = add_ln176_3_reg_629.read();
        add_ln176_3_reg_629_pp0_iter5_reg = add_ln176_3_reg_629_pp0_iter4_reg.read();
        add_ln176_5_reg_634_pp0_iter4_reg = add_ln176_5_reg_634.read();
        hwin_1_1_i_load_reg_509_pp0_iter2_reg = hwin_1_1_i_load_reg_509_pp0_iter1_reg.read();
        icmp_ln168_reg_555_pp0_iter2_reg = icmp_ln168_reg_555_pp0_iter1_reg.read();
        icmp_ln168_reg_555_pp0_iter3_reg = icmp_ln168_reg_555_pp0_iter2_reg.read();
        icmp_ln168_reg_555_pp0_iter4_reg = icmp_ln168_reg_555_pp0_iter3_reg.read();
        icmp_ln168_reg_555_pp0_iter5_reg = icmp_ln168_reg_555_pp0_iter4_reg.read();
        icmp_ln178_reg_575_pp0_iter2_reg = icmp_ln178_reg_575_pp0_iter1_reg.read();
        icmp_ln178_reg_575_pp0_iter3_reg = icmp_ln178_reg_575_pp0_iter2_reg.read();
        icmp_ln178_reg_575_pp0_iter4_reg = icmp_ln178_reg_575_pp0_iter3_reg.read();
        icmp_ln178_reg_575_pp0_iter5_reg = icmp_ln178_reg_575_pp0_iter4_reg.read();
        icmp_ln178_reg_575_pp0_iter6_reg = icmp_ln178_reg_575_pp0_iter5_reg.read();
        tmp_2_reg_569_pp0_iter2_reg = tmp_2_reg_569_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_reg_555_pp0_iter3_reg.read()))) {
        add_ln176_9_reg_649 = add_ln176_9_fu_399_p2.read();
        mul_ln176_2_reg_644 = grp_fu_340_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        bound_reg_504 = grp_fu_165_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, height_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_empty_n.read())))) {
        height_read_reg_483 = height_dout.read();
        width_read_reg_488 = width_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        hwin_1_1_i_fu_72 = hwin_1_fu_76.read();
        hwin_1_fu_76 = hwin_2_fu_80.read();
        hwin_2_fu_80 = hwin_3_fu_84.read();
        hwin_3_fu_84 = hwin_4_fu_88.read();
        hwin_4_fu_88 = hwin_5_fu_92.read();
        hwin_5_fu_92 = hwin_6_fu_96.read();
        hwin_6_fu_96 = hwin_7_fu_100.read();
        hwin_7_fu_100 = hwin_8_fu_104.read();
        hwin_8_fu_104 = hwin_9_fu_108.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        hwin_1_1_i_load_reg_509 = hwin_1_1_i_fu_72.read();
        hwin_1_1_i_load_reg_509_pp0_iter1_reg = hwin_1_1_i_load_reg_509.read();
        hwin_3_load_reg_525 = hwin_3_fu_84.read();
        hwin_3_load_reg_525_pp0_iter1_reg = hwin_3_load_reg_525.read();
        hwin_6_load_reg_540 = hwin_6_fu_96.read();
        hwin_7_load_reg_545 = hwin_7_fu_100.read();
        icmp_ln168_reg_555 = icmp_ln168_fu_210_p2.read();
        icmp_ln168_reg_555_pp0_iter1_reg = icmp_ln168_reg_555.read();
        icmp_ln178_reg_575_pp0_iter1_reg = icmp_ln178_reg_575.read();
        tmp_2_reg_569_pp0_iter1_reg = tmp_2_reg_569.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        hwin_9_fu_108 = src_V_0_data_out.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln178_reg_575 = icmp_ln178_fu_313_p2.read();
        tmp_2_reg_569 = src_V_0_data_out.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_reg_555_pp0_iter1_reg.read()))) {
        mul_ln176_1_reg_589 = grp_fu_283_p2.read();
        mul_ln176_3_reg_594 = grp_fu_289_p2.read();
        mul_ln176_4_reg_599 = grp_fu_295_p2.read();
        mul_ln176_7_reg_604 = grp_fu_301_p2.read();
        mul_ln176_8_reg_609 = grp_fu_307_p2.read();
        mul_ln176_reg_584 = grp_fu_277_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_load_A.read())) {
        src_V_0_payload_A = src_V_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_load_B.read())) {
        src_V_0_payload_B = src_V_TDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_reg_555_pp0_iter5_reg.read()))) {
        tmp_reg_659 = tmp_fu_417_p2.read();
    }
}

void Loop_HConvH_proc8::thread_add_ln168_fu_215_p2() {
    add_ln168_fu_215_p2 = (!indvar_flatten_reg_137.read().is_01() || !ap_const_lv64_1.is_01())? sc_lv<64>(): (sc_biguint<64>(indvar_flatten_reg_137.read()) + sc_biguint<64>(ap_const_lv64_1));
}

void Loop_HConvH_proc8::thread_add_ln176_10_fu_408_p2() {
    add_ln176_10_fu_408_p2 = (!add_ln176_9_reg_649.read().is_01() || !add_ln176_6_fu_404_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln176_9_reg_649.read()) + sc_biguint<32>(add_ln176_6_fu_404_p2.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_1_fu_371_p2() {
    add_ln176_1_fu_371_p2 = (!add_ln176_fu_365_p2.read().is_01() || !shl_ln176_3_fu_360_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln176_fu_365_p2.read()) + sc_biguint<32>(shl_ln176_3_fu_360_p2.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_2_fu_377_p2() {
    add_ln176_2_fu_377_p2 = (!mul_ln176_reg_584.read().is_01() || !mul_ln176_1_reg_589.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln176_reg_584.read()) + sc_biguint<32>(mul_ln176_1_reg_589.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_3_fu_381_p2() {
    add_ln176_3_fu_381_p2 = (!add_ln176_2_fu_377_p2.read().is_01() || !shl_ln176_1_fu_350_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln176_2_fu_377_p2.read()) + sc_biguint<32>(shl_ln176_1_fu_350_p2.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_4_fu_413_p2() {
    add_ln176_4_fu_413_p2 = (!add_ln176_3_reg_629_pp0_iter5_reg.read().is_01() || !add_ln176_1_reg_624_pp0_iter5_reg.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln176_3_reg_629_pp0_iter5_reg.read()) + sc_biguint<32>(add_ln176_1_reg_624_pp0_iter5_reg.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_5_fu_387_p2() {
    add_ln176_5_fu_387_p2 = (!mul_ln176_3_reg_594.read().is_01() || !mul_ln176_4_reg_599.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln176_3_reg_594.read()) + sc_biguint<32>(mul_ln176_4_reg_599.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_6_fu_404_p2() {
    add_ln176_6_fu_404_p2 = (!add_ln176_5_reg_634_pp0_iter4_reg.read().is_01() || !mul_ln176_2_reg_644.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln176_5_reg_634_pp0_iter4_reg.read()) + sc_biguint<32>(mul_ln176_2_reg_644.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_7_fu_395_p2() {
    add_ln176_7_fu_395_p2 = (!mul_ln176_5_reg_614.read().is_01() || !mul_ln176_6_reg_619.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln176_5_reg_614.read()) + sc_biguint<32>(mul_ln176_6_reg_619.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_8_fu_391_p2() {
    add_ln176_8_fu_391_p2 = (!mul_ln176_7_reg_604.read().is_01() || !mul_ln176_8_reg_609.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln176_7_reg_604.read()) + sc_biguint<32>(mul_ln176_8_reg_609.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_9_fu_399_p2() {
    add_ln176_9_fu_399_p2 = (!add_ln176_8_reg_639.read().is_01() || !add_ln176_7_fu_395_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln176_8_reg_639.read()) + sc_biguint<32>(add_ln176_7_fu_395_p2.read()));
}

void Loop_HConvH_proc8::thread_add_ln176_fu_365_p2() {
    add_ln176_fu_365_p2 = (!shl_ln176_2_fu_355_p2.read().is_01() || !shl_ln176_fu_345_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln176_2_fu_355_p2.read()) + sc_biguint<32>(shl_ln176_fu_345_p2.read()));
}

void Loop_HConvH_proc8::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[4];
}

void Loop_HConvH_proc8::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_HConvH_proc8::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[5];
}

void Loop_HConvH_proc8::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Loop_HConvH_proc8::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void Loop_HConvH_proc8::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_HConvH_proc8::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln178_reg_575_pp0_iter6_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, hconv_V_full_n.read())));
}

void Loop_HConvH_proc8::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln178_reg_575_pp0_iter6_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, hconv_V_full_n.read())));
}

void Loop_HConvH_proc8::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln178_reg_575_pp0_iter6_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, hconv_V_full_n.read())));
}

void Loop_HConvH_proc8::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, height_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_empty_n.read()));
}

void Loop_HConvH_proc8::thread_ap_block_state10_pp0_stage0_iter5() {
    ap_block_state10_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_HConvH_proc8::thread_ap_block_state11_pp0_stage0_iter6() {
    ap_block_state11_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_HConvH_proc8::thread_ap_block_state12_pp0_stage0_iter7() {
    ap_block_state12_pp0_stage0_iter7 = (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln178_reg_575_pp0_iter6_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, hconv_V_full_n.read()));
}

void Loop_HConvH_proc8::thread_ap_block_state5_pp0_stage0_iter0() {
    ap_block_state5_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_0_vld_out.read()));
}

void Loop_HConvH_proc8::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_HConvH_proc8::thread_ap_block_state7_pp0_stage0_iter2() {
    ap_block_state7_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_HConvH_proc8::thread_ap_block_state8_pp0_stage0_iter3() {
    ap_block_state8_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_HConvH_proc8::thread_ap_block_state9_pp0_stage0_iter4() {
    ap_block_state9_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_HConvH_proc8::thread_ap_condition_pp0_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln168_fu_210_p2.read())) {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_HConvH_proc8::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_HConvH_proc8::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void Loop_HConvH_proc8::thread_grp_fu_165_p0() {
    grp_fu_165_p0 =  (sc_lv<32>) (grp_fu_165_p00.read());
}

void Loop_HConvH_proc8::thread_grp_fu_165_p00() {
    grp_fu_165_p00 = esl_zext<64,32>(width_read_reg_488.read());
}

void Loop_HConvH_proc8::thread_grp_fu_165_p1() {
    grp_fu_165_p1 =  (sc_lv<32>) (grp_fu_165_p10.read());
}

void Loop_HConvH_proc8::thread_grp_fu_165_p10() {
    grp_fu_165_p10 = esl_zext<64,32>(height_read_reg_483.read());
}

void Loop_HConvH_proc8::thread_grp_fu_277_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_277_ce = ap_const_logic_1;
    } else {
        grp_fu_277_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_277_p0() {
    grp_fu_277_p0 =  (sc_lv<8>) (ap_const_lv32_6F);
}

void Loop_HConvH_proc8::thread_grp_fu_283_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_283_ce = ap_const_logic_1;
    } else {
        grp_fu_283_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_283_p0() {
    grp_fu_283_p0 =  (sc_lv<10>) (ap_const_lv32_10A);
}

void Loop_HConvH_proc8::thread_grp_fu_289_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_289_ce = ap_const_logic_1;
    } else {
        grp_fu_289_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_289_p0() {
    grp_fu_289_p0 =  (sc_lv<11>) (ap_const_lv32_2D4);
}

void Loop_HConvH_proc8::thread_grp_fu_295_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_295_ce = ap_const_logic_1;
    } else {
        grp_fu_295_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_295_p0() {
    grp_fu_295_p0 =  (sc_lv<11>) (ap_const_lv32_335);
}

void Loop_HConvH_proc8::thread_grp_fu_301_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_301_ce = ap_const_logic_1;
    } else {
        grp_fu_301_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_301_p0() {
    grp_fu_301_p0 =  (sc_lv<10>) (ap_const_lv32_10A);
}

void Loop_HConvH_proc8::thread_grp_fu_307_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_307_ce = ap_const_logic_1;
    } else {
        grp_fu_307_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_307_p0() {
    grp_fu_307_p0 =  (sc_lv<8>) (ap_const_lv32_6F);
}

void Loop_HConvH_proc8::thread_grp_fu_330_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_330_ce = ap_const_logic_1;
    } else {
        grp_fu_330_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_330_p0() {
    grp_fu_330_p0 =  (sc_lv<11>) (ap_const_lv32_2D4);
}

void Loop_HConvH_proc8::thread_grp_fu_335_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_335_ce = ap_const_logic_1;
    } else {
        grp_fu_335_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_335_p0() {
    grp_fu_335_p0 =  (sc_lv<10>) (ap_const_lv32_1F2);
}

void Loop_HConvH_proc8::thread_grp_fu_340_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_340_ce = ap_const_logic_1;
    } else {
        grp_fu_340_ce = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_grp_fu_340_p0() {
    grp_fu_340_p0 =  (sc_lv<10>) (ap_const_lv32_1F2);
}

void Loop_HConvH_proc8::thread_hconv_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln178_reg_575_pp0_iter6_reg.read()))) {
        hconv_V_blk_n = hconv_V_full_n.read();
    } else {
        hconv_V_blk_n = ap_const_logic_1;
    }
}

void Loop_HConvH_proc8::thread_hconv_V_din() {
    hconv_V_din = tmp_reg_659.read();
}

void Loop_HConvH_proc8::thread_hconv_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln178_reg_575_pp0_iter6_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        hconv_V_write = ap_const_logic_1;
    } else {
        hconv_V_write = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_height_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        height_blk_n = height_empty_n.read();
    } else {
        height_blk_n = ap_const_logic_1;
    }
}

void Loop_HConvH_proc8::thread_height_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, height_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_empty_n.read())))) {
        height_read = ap_const_logic_1;
    } else {
        height_read = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_icmp_ln168_fu_210_p2() {
    icmp_ln168_fu_210_p2 = (!indvar_flatten_reg_137.read().is_01() || !bound_reg_504.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_137.read() == bound_reg_504.read());
}

void Loop_HConvH_proc8::thread_icmp_ln169_fu_205_p2() {
    icmp_ln169_fu_205_p2 = (!zext_ln169_fu_201_p1.read().is_01() || !width_read_reg_488.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln169_fu_201_p1.read()) < sc_bigint<32>(width_read_reg_488.read()));
}

void Loop_HConvH_proc8::thread_icmp_ln178_fu_313_p2() {
    icmp_ln178_fu_313_p2 = (!select_ln169_fu_269_p3.read().is_01() || !ap_const_lv11_9.is_01())? sc_lv<1>(): (sc_biguint<11>(select_ln169_fu_269_p3.read()) > sc_biguint<11>(ap_const_lv11_9));
}

void Loop_HConvH_proc8::thread_internal_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void Loop_HConvH_proc8::thread_row_fu_324_p2() {
    row_fu_324_p2 = (!select_ln169_fu_269_p3.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(select_ln169_fu_269_p3.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void Loop_HConvH_proc8::thread_select_ln169_fu_269_p3() {
    select_ln169_fu_269_p3 = (!icmp_ln169_fu_205_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln169_fu_205_p2.read()[0].to_bool())? row_0_i_i_reg_148.read(): ap_const_lv11_0);
}

void Loop_HConvH_proc8::thread_shl_ln176_1_fu_350_p2() {
    shl_ln176_1_fu_350_p2 = (!ap_const_lv32_2.is_01())? sc_lv<32>(): hwin_1_1_i_load_reg_509_pp0_iter2_reg.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void Loop_HConvH_proc8::thread_shl_ln176_2_fu_355_p2() {
    shl_ln176_2_fu_355_p2 = (!ap_const_lv32_5.is_01())? sc_lv<32>(): tmp_2_reg_569_pp0_iter2_reg.read() << (unsigned short)ap_const_lv32_5.to_uint();
}

void Loop_HConvH_proc8::thread_shl_ln176_3_fu_360_p2() {
    shl_ln176_3_fu_360_p2 = (!ap_const_lv32_2.is_01())? sc_lv<32>(): tmp_2_reg_569_pp0_iter2_reg.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void Loop_HConvH_proc8::thread_shl_ln176_fu_345_p2() {
    shl_ln176_fu_345_p2 = (!ap_const_lv32_5.is_01())? sc_lv<32>(): hwin_1_1_i_load_reg_509_pp0_iter2_reg.read() << (unsigned short)ap_const_lv32_5.to_uint();
}

void Loop_HConvH_proc8::thread_src_V_0_ack_in() {
    src_V_0_ack_in = src_V_0_state.read()[1];
}

void Loop_HConvH_proc8::thread_src_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        src_V_0_ack_out = ap_const_logic_1;
    } else {
        src_V_0_ack_out = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_src_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, src_V_0_sel.read())) {
        src_V_0_data_out = src_V_0_payload_B.read();
    } else {
        src_V_0_data_out = src_V_0_payload_A.read();
    }
}

void Loop_HConvH_proc8::thread_src_V_0_load_A() {
    src_V_0_load_A = (src_V_0_state_cmp_full.read() & ~src_V_0_sel_wr.read());
}

void Loop_HConvH_proc8::thread_src_V_0_load_B() {
    src_V_0_load_B = (src_V_0_sel_wr.read() & src_V_0_state_cmp_full.read());
}

void Loop_HConvH_proc8::thread_src_V_0_sel() {
    src_V_0_sel = src_V_0_sel_rd.read();
}

void Loop_HConvH_proc8::thread_src_V_0_state_cmp_full() {
    src_V_0_state_cmp_full =  (sc_logic) ((!src_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(src_V_0_state.read() != ap_const_lv2_1))[0];
}

void Loop_HConvH_proc8::thread_src_V_0_vld_in() {
    src_V_0_vld_in = src_V_TVALID.read();
}

void Loop_HConvH_proc8::thread_src_V_0_vld_out() {
    src_V_0_vld_out = src_V_0_state.read()[0];
}

void Loop_HConvH_proc8::thread_src_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln168_fu_210_p2.read()))) {
        src_V_TDATA_blk_n = src_V_0_state.read()[0];
    } else {
        src_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void Loop_HConvH_proc8::thread_src_V_TREADY() {
    src_V_TREADY = src_V_0_state.read()[1];
}

void Loop_HConvH_proc8::thread_start_out() {
    start_out = real_start.read();
}

void Loop_HConvH_proc8::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_tmp_fu_417_p2() {
    tmp_fu_417_p2 = (!add_ln176_10_reg_654.read().is_01() || !add_ln176_4_fu_413_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln176_10_reg_654.read()) + sc_biguint<32>(add_ln176_4_fu_413_p2.read()));
}

void Loop_HConvH_proc8::thread_width_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        width_blk_n = width_empty_n.read();
    } else {
        width_blk_n = ap_const_logic_1;
    }
}

void Loop_HConvH_proc8::thread_width_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, height_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_empty_n.read())))) {
        width_read = ap_const_logic_1;
    } else {
        width_read = ap_const_logic_0;
    }
}

void Loop_HConvH_proc8::thread_zext_ln169_fu_201_p1() {
    zext_ln169_fu_201_p1 = esl_zext<32,11>(row_0_i_i_reg_148.read());
}

void Loop_HConvH_proc8::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, height_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 16 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter6.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln168_fu_210_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter6.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln168_fu_210_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

}

