// ==============================================================
// RTL generated by Scout HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.0
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hier_func_hier_func_HH_
#define _hier_func_hier_func_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct hier_func_hier_func : public sc_module {
    // Port declarations 10
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > A;
    sc_in< sc_lv<32> > B;
    sc_out< sc_lv<32> > C;
    sc_out< sc_logic > C_ap_vld;
    sc_out< sc_lv<32> > D;
    sc_out< sc_logic > D_ap_vld;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    hier_func_hier_func(sc_module_name name);
    SC_HAS_PROCESS(hier_func_hier_func);

    ~hier_func_hier_func();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<32> > add_ln50_fu_62_p2;
    sc_signal< sc_lv<31> > trunc_ln_fu_74_p4;
    sc_signal< sc_lv<32> > sub_ln51_fu_68_p2;
    sc_signal< sc_lv<30> > trunc_ln1_fu_89_p4;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_C();
    void thread_C_ap_vld();
    void thread_D();
    void thread_D_ap_vld();
    void thread_add_ln50_fu_62_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_sub_ln51_fu_68_p2();
    void thread_trunc_ln1_fu_89_p4();
    void thread_trunc_ln_fu_74_p4();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
